_target_: meds_testing_helpers.dataset_generator.MEDSDataDFGenerator

static_vocab_size: 16
vocab_size: ???

start_datetime_per_subject:
  _target_: meds_testing_helpers.dataset_generator.DatetimeGenerator
  X: ???
  freq: null

time_between_events_per_subj:
  _target_: meds_testing_helpers.dataset_generator.PositiveNumGenerator
  X: ???
  freq: null

frac_code_occurrences_with_value:
  _target_: meds_testing_helpers.dataset_generator.ProportionGenerator
  X: ???
  freq: null

num_events_per_subject:
  _target_: meds_testing_helpers.dataset_generator.PositiveIntGenerator
  X: ???
  freq: null

num_measurements_per_event:
  _target_: meds_testing_helpers.dataset_generator.PositiveIntGenerator
  X: ???
  freq: null

num_static_measurements_per_subject:
  _target_: meds_testing_helpers.dataset_generator.PositiveIntGenerator
  X: ???
  freq: null
