defaults:
  - _self_
  - override hydra/job_logging=disabled
  - override hydra/hydra_logging=disabled

seed: 1
dataset_dir: ???
output_fp: ???
do_overwrite: False

hydra:
  output_subdir: null
  run:
    dir: .
